apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: robot-shop
  labels:
    service: web
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    service: web
  type: LoadBalancer
